### ISSUE TITLE
a problem of flieerror

### ISSUE THREAD

**Issue by tigriyang** [Meowcolm024/FGO-One#6]
device:mi 6  android8.0 
desktop:windows 10.17763.349
------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:/FGO-One-master/main.py", line 21, in <module>
    end = s.recognize()
  File "E:\FGO-One-master\interface\Major.py", line 72, in recognize
    self.get_battle()
  File "E:\FGO-One-master\interface\Major.py", line 64, in get_battle
    split()
  File "E:\FGO-One-master\util\split.py", line 65, in split
    init()
  File "E:\FGO-One-master\util\split.py", line 17, in init
    region.save("./temp/out.png")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 1991, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './temp/out.png'

Process finished with exit code 1
-----------------------------------------------------------------------------------------
i am not good at coding,so i can't find out the solution.

**Comment by Meowcolm024** [comment]
Sorry, I haven't tested it on Windows. However, from the traceback, I thought could be something about the PIL library.
So try the create directory __temp__ .
Or try to delete __./__ from the code (I don't have a computer right now, but I would check it out later)

**Comment by tigriyang** [comment]
I create the directory and then queastion solved,thanks.
However new issues come out.
here is the trace back
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:/FGO-One-0.3.0-alpha/main.py", line 21, in <module>
    end = s.recognize()
  File "E:\FGO-One-0.3.0-alpha\interface\Major.py", line 72, in recognize
    self.get_battle()
  File "E:\FGO-One-0.3.0-alpha\interface\Major.py", line 65, in get_battle
    combat = Battle()
  File "E:\FGO-One-0.3.0-alpha\cards\Combat.py", line 20, in __init__
    self.card_crd = self.get_np()
  File "E:\FGO-One-0.3.0-alpha\cards\Combat.py", line 29, in get_np
    if float(a) / float(b) == 1:
ValueError: could not convert string to float: 'r'
------------------------------------------------------------------------------------------
now i can run it every turn.but it can't ranning continuously.

**Comment by Meowcolm024** [comment]
Please see issue [#5](https://github.com/Meowcolm024/FGO-One/issues/5)
